language: csharp
solution: nsds.sln
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore nsds.sln
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner
services:
  - redis-server
env:
  - REDIS_SERVER=127.0.0.1:6379
script:
  - xbuild /p:Configuration=Release nsds.sln
  - mono ./testrunner/NUnit.Runners.3.0.1/tools/nunit-console.exe ./nsds.RedisDictionaryService.Test/bin/release/nsds.RedisDictionaryService.Test.dll